[2024-11-14T15:22:32.098+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T15:22:32.682+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.choose_best_model manual__2024-11-14T15:21:31.015862+00:00 [queued]>
[2024-11-14T15:22:33.044+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.choose_best_model manual__2024-11-14T15:21:31.015862+00:00 [queued]>
[2024-11-14T15:22:33.066+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-14T15:22:33.488+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-11-14 15:21:31.015862+00:00
[2024-11-14T15:22:33.905+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T15:22:33.954+0000] {standard_task_runner.py:72} INFO - Started process 163 to run task
[2024-11-14T15:22:33.982+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hello_world_dag', 'choose_best_model', 'manual__2024-11-14T15:21:31.015862+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/hello_world_dag.py', '--cfg-path', '/tmp/tmpmwd52hu3']
[2024-11-14T15:22:34.108+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask choose_best_model
[2024-11-14T15:22:35.270+0000] {task_command.py:467} INFO - Running <TaskInstance: hello_world_dag.choose_best_model manual__2024-11-14T15:21:31.015862+00:00 [running]> on host e14bbb8637e8
[2024-11-14T15:22:43.882+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world_dag' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T15:21:31.015862+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T15:21:31.015862+00:00'
[2024-11-14T15:22:43.889+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-14T15:22:43.896+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-14T15:22:43.904+0000] {logging_mixin.py:190} INFO - Current task name:choose_best_model state:running start_date:2024-11-14 15:22:32.718100+00:00
[2024-11-14T15:22:43.913+0000] {logging_mixin.py:190} INFO - Dag name:hello_world_dag and current dag run status:running
[2024-11-14T15:22:43.931+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-14T15:22:43.939+0000] {baseoperator.py:416} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-11-14T15:22:44.149+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hello_world_dag.py", line 17, in _choose_best_model
    best_accuracy = max(accuracies)
                    ^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
[2024-11-14T15:22:44.265+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-14T15:22:44.282+0000] {logging_mixin.py:190} INFO - Task start:2024-11-14 15:22:32.718100+00:00 end:2024-11-14 15:22:44.265447+00:00 duration:11.547347
[2024-11-14T15:22:44.293+0000] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): choose_best_model> dag:<DAG: hello_world_dag> dagrun:<DagRun hello_world_dag @ 2024-11-14 15:21:31.015862+00:00: manual__2024-11-14T15:21:31.015862+00:00, state:running, queued_at: 2024-11-14 15:21:31.054149+00:00. externally triggered: True>
[2024-11-14T15:22:44.302+0000] {logging_mixin.py:190} INFO - Failure caused by max() iterable argument is empty
[2024-11-14T15:22:44.310+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=hello_world_dag, task_id=choose_best_model, run_id=manual__2024-11-14T15:21:31.015862+00:00, execution_date=20241114T152131, start_date=20241114T152232, end_date=20241114T152244
[2024-11-14T15:22:44.682+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-14T15:22:44.747+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task choose_best_model (max() iterable argument is empty; 163)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hello_world_dag.py", line 17, in _choose_best_model
    best_accuracy = max(accuracies)
                    ^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
[2024-11-14T15:22:45.323+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-14T15:22:45.338+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
